# Generated by Django 2.2 on 2019-04-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('m1', models.CharField(max_length=256, null=True)),
                ('m2', models.CharField(max_length=256, null=True)),
                ('sex', models.CharField(choices=[('0', '未知'), ('1', '男'), ('2', '女')], default=0, max_length=2,
                                         verbose_name='性别')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
