# Generated by Django 2.2 on 2019-04-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=128, null=True, unique=True, verbose_name='登录名')),
                ('password', models.CharField(max_length=256, null=True, verbose_name='密码')),
                ('rname', models.CharField(max_length=256, null=True, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=256, null=True, verbose_name='电话')),
                ('email', models.CharField(max_length=256, null=True, verbose_name='邮箱')),
                (
                'state', models.IntegerField(choices=[(0, '默认'), (1, '正常'), (-1, '删除')], default=0, verbose_name='状态')),
                ('tp', models.IntegerField(choices=[(0, '默认'), (1, '普通用户'), (2, '管理员'), (9, '系统管理员')], default=0,
                                           verbose_name='类型')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
